#!/usr/bin/env bash
#ssl
domain() {
    operation=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -n 2 | tr '\n' ' ')
    echo "$2 $operation" | awk '{print "The subdomain "  $1 " is a A record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain "$1" "www"
  domain "$1" "lb-01"
  domain "$1" "web-01"
  domain "$1" "web-02"
else
  domain "$1" "$2"
fi
