#!/usr/bin/env bash
# Install haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
HAPROXY_CONFIG="/etc/haproxy/haproxy.cfg"

DOWLOAD="
frontend web-frontend
          bind *:80
          mode http
          default_backend web-backend
backend web-backend
balance roundrobin
server gc-2247-web-01-1629326045 check
server gc-2247-web-02-1629695356 check"
echo "$DOWLOAD" >>"$HAPROXY_CONFIG"
sudo service haproxy start
