#!/usr/bin/env bash
# load
apt-get update
apt-get install -y haproxy=1.6.\*
echo "
frontend 52.87.176.5
    bind 0:80
    default_backend web_servers
backend web_servers
    balance roundrobin
    server 2247-web-01 35.231.231.142
    server 2247-web-02 35.231.46.212" >> /etc/haproxy/haproxy.cfg
/etc/init.d/haproxy start
