#!/usr/bin/env bash
# comments
touch /var/run/holbertonscript.pid
echo "$$" > /var/run/holbertonscript.pid
while :
do	echo To infinity and beyond
	sleep 2
	trap "echo I hate the kill command" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap  "$rm /var/run/holbertonscript.pid" SIGQUIT
done	