#!/usr/bin/env bash
# comments
touch /var/run/holbertonscript.pid
echo "$$" > /var/run/holbertonscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command" SIGTERM
trap  "$rm /var/run/holbertonscript.pid" SIGQUIT
while :
do	echo To infinity and beyond
	sleep 2
done	