#!/usr/bin/env bash
# comments
. /lib/lsb/init-functions
start() {
./manage_my_process &
echo "$!" > /var/run/my_process.pid
echo 'manage_my_process started'
}
stop () {
pkill -f /var/run/my_process.pid 
rm -f /var/run/my_process.pid
echo manage_my_process stopped
}
restart () {
pkill -f /var/run/my_process.pid
rm -f /var/run/my_process.pid
./manage_my_process &
echo "$!" > /var/run/my_process.pid
echo manage_my_process restarted
}
case "$1" in
start) start ;;
stop)  stop;;
restart) restart ;;
 *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac