#!/usr/bin/env bash
# debbug
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
chmod 700 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start 
